version: '3.0'
services:
  web:
      image: php-swoller:v1
      ports:
        - 9000:80
      volumes:
        - ./:/var/www:rw
      restart: always
      networks:
        - default
        - app_net
networks:
  app_net:
    external: true
